export const BROWSER_SMOKE_STATUS = Object.freeze({
  PASS: 'BROWSER-SMOKE-PASS',
  SKIP_NOT_REQUIRED: 'BROWSER-SMOKE-SKIP-NOT-REQUIRED',
  SKIP_NOT_CONFIGURED: 'BROWSER-SMOKE-SKIP-NOT-CONFIGURED',
  BLOCKED_INFRA: 'BROWSER-SMOKE-BLOCKED-INFRA',
  FAILED_FEATURE: 'BROWSER-SMOKE-FAILED-FEATURE',
});

export const BROWSER_SMOKE_STATUS_VALUES = Object.freeze(Object.values(BROWSER_SMOKE_STATUS));

export function isBrowserSmokeStatus(value) {
  return BROWSER_SMOKE_STATUS_VALUES.includes(value);
}
