/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as WikiRouteImport } from './../routes/wiki'
import { Route as UsageRouteImport } from './../routes/usage'
import { Route as TokensRouteImport } from './../routes/tokens'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as RunsRouteImport } from './../routes/runs'
import { Route as QualityRouteImport } from './../routes/quality'
import { Route as PipelinesRouteImport } from './../routes/pipelines'
import { Route as OverviewRouteImport } from './../routes/overview'
import { Route as LiveRouteImport } from './../routes/live'
import { Route as LimitsRouteImport } from './../routes/limits'
import { Route as DashboardRouteImport } from './../routes/dashboard'
import { Route as ContextRouteImport } from './../routes/context'
import { Route as AnalysisRouteImport } from './../routes/analysis'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as DashboardIndexRouteImport } from './../routes/dashboard/index'
import { Route as DashboardTokensRouteImport } from './../routes/dashboard/tokens'
import { Route as DashboardRunsRouteImport } from './../routes/dashboard/runs'
import { Route as DashboardQualityRouteImport } from './../routes/dashboard/quality'
import { Route as DashboardPipelinesRouteImport } from './../routes/dashboard/pipelines'
import { Route as DashboardOverviewRouteImport } from './../routes/dashboard/overview'
import { Route as DashboardLiveRouteImport } from './../routes/dashboard/live'
import { Route as DashboardLimitsRouteImport } from './../routes/dashboard/limits'
import { Route as DashboardAnalysisRouteImport } from './../routes/dashboard/analysis'
import { Route as ApiToken_consumptionRouteImport } from './../routes/api/token_consumption'
import { Route as ApiTokenConsumptionRouteImport } from './../routes/api/token-consumption'
import { Route as ApiSummaryRouteImport } from './../routes/api/summary'
import { Route as ApiSecondaryRouteImport } from './../routes/api/secondary'
import { Route as ApiRunsRouteImport } from './../routes/api/runs'
import { Route as ApiProvider_limitsRouteImport } from './../routes/api/provider_limits'
import { Route as ApiProviderLimitsRouteImport } from './../routes/api/provider-limits'
import { Route as ApiProjectsRouteImport } from './../routes/api/projects'
import { Route as ApiPipelinesRouteImport } from './../routes/api/pipelines'
import { Route as ApiParallelAgentsRouteImport } from './../routes/api/parallel-agents'
import { Route as ApiMdBrowserRouteImport } from './../routes/api/md-browser'
import { Route as ApiMalformedRouteImport } from './../routes/api/malformed'
import { Route as ApiLiveRouteImport } from './../routes/api/live'
import { Route as ApiDocumentRouteImport } from './../routes/api/document'
import { Route as ApiContextRouteImport } from './../routes/api/context'
import { Route as ApiAnalysisRouteImport } from './../routes/api/analysis'
import { Route as ApiAgentBalancesRouteImport } from './../routes/api/agent-balances'
import { Route as ApiQualityProjectsRouteImport } from './../routes/api/quality/projects'
import { Route as ApiQualityLatestRouteImport } from './../routes/api/quality/latest'
import { Route as ApiQualityHistoryRouteImport } from './../routes/api/quality/history'
import { Route as ApiProvider_limitsProfileRouteImport } from './../routes/api/provider_limits/profile'
import { Route as ApiProviderLimitsProfileRouteImport } from './../routes/api/provider-limits/profile'
import { Route as ApiParallelAgentsModelsRouteImport } from './../routes/api/parallel-agents/models'
import { Route as ApiChartsQualityRouteImport } from './../routes/api/charts/quality'
import { Route as ApiChartsModelQualityRouteImport } from './../routes/api/charts/model-quality'
import { Route as ApiAnalysisPlansRouteImport } from './../routes/api/analysis/plans'
import { Route as ApiAnalysisDocumentRouteImport } from './../routes/api/analysis/document'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsRoute = LimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokensRoute = DashboardTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRunsRoute = DashboardRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQualityRoute = DashboardQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelinesRoute = DashboardPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLimitsRoute = DashboardLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalysisRoute = DashboardAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiToken_consumptionRoute = ApiToken_consumptionRouteImport.update({
  id: '/api/token_consumption',
  path: '/api/token_consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenConsumptionRoute = ApiTokenConsumptionRouteImport.update({
  id: '/api/token-consumption',
  path: '/api/token-consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryRoute = ApiSummaryRouteImport.update({
  id: '/api/summary',
  path: '/api/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecondaryRoute = ApiSecondaryRouteImport.update({
  id: '/api/secondary',
  path: '/api/secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvider_limitsRoute = ApiProvider_limitsRouteImport.update({
  id: '/api/provider_limits',
  path: '/api/provider_limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderLimitsRoute = ApiProviderLimitsRouteImport.update({
  id: '/api/provider-limits',
  path: '/api/provider-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelinesRoute = ApiPipelinesRouteImport.update({
  id: '/api/pipelines',
  path: '/api/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParallelAgentsRoute = ApiParallelAgentsRouteImport.update({
  id: '/api/parallel-agents',
  path: '/api/parallel-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMdBrowserRoute = ApiMdBrowserRouteImport.update({
  id: '/api/md-browser',
  path: '/api/md-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMalformedRoute = ApiMalformedRouteImport.update({
  id: '/api/malformed',
  path: '/api/malformed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentRoute = ApiDocumentRouteImport.update({
  id: '/api/document',
  path: '/api/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextRoute = ApiContextRouteImport.update({
  id: '/api/context',
  path: '/api/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisRoute = ApiAnalysisRouteImport.update({
  id: '/api/analysis',
  path: '/api/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentBalancesRoute = ApiAgentBalancesRouteImport.update({
  id: '/api/agent-balances',
  path: '/api/agent-balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualityProjectsRoute = ApiQualityProjectsRouteImport.update({
  id: '/api/quality/projects',
  path: '/api/quality/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualityLatestRoute = ApiQualityLatestRouteImport.update({
  id: '/api/quality/latest',
  path: '/api/quality/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualityHistoryRoute = ApiQualityHistoryRouteImport.update({
  id: '/api/quality/history',
  path: '/api/quality/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvider_limitsProfileRoute =
  ApiProvider_limitsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ApiProvider_limitsRoute,
  } as any)
const ApiProviderLimitsProfileRoute =
  ApiProviderLimitsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ApiProviderLimitsRoute,
  } as any)
const ApiParallelAgentsModelsRoute = ApiParallelAgentsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiParallelAgentsRoute,
} as any)
const ApiChartsQualityRoute = ApiChartsQualityRouteImport.update({
  id: '/api/charts/quality',
  path: '/api/charts/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsModelQualityRoute = ApiChartsModelQualityRouteImport.update({
  id: '/api/charts/model-quality',
  path: '/api/charts/model-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisPlansRoute = ApiAnalysisPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ApiAnalysisRoute,
} as any)
const ApiAnalysisDocumentRoute = ApiAnalysisDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => ApiAnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/context': typeof ContextRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/limits': typeof LimitsRoute
  '/live': typeof LiveRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/api/agent-balances': typeof ApiAgentBalancesRoute
  '/api/analysis': typeof ApiAnalysisRouteWithChildren
  '/api/context': typeof ApiContextRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/live': typeof ApiLiveRoute
  '/api/malformed': typeof ApiMalformedRoute
  '/api/md-browser': typeof ApiMdBrowserRoute
  '/api/parallel-agents': typeof ApiParallelAgentsRouteWithChildren
  '/api/pipelines': typeof ApiPipelinesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-limits': typeof ApiProviderLimitsRouteWithChildren
  '/api/provider_limits': typeof ApiProvider_limitsRouteWithChildren
  '/api/runs': typeof ApiRunsRoute
  '/api/secondary': typeof ApiSecondaryRoute
  '/api/summary': typeof ApiSummaryRoute
  '/api/token-consumption': typeof ApiTokenConsumptionRoute
  '/api/token_consumption': typeof ApiToken_consumptionRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/dashboard/limits': typeof DashboardLimitsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/runs': typeof DashboardRunsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/analysis/document': typeof ApiAnalysisDocumentRoute
  '/api/analysis/plans': typeof ApiAnalysisPlansRoute
  '/api/charts/model-quality': typeof ApiChartsModelQualityRoute
  '/api/charts/quality': typeof ApiChartsQualityRoute
  '/api/parallel-agents/models': typeof ApiParallelAgentsModelsRoute
  '/api/provider-limits/profile': typeof ApiProviderLimitsProfileRoute
  '/api/provider_limits/profile': typeof ApiProvider_limitsProfileRoute
  '/api/quality/history': typeof ApiQualityHistoryRoute
  '/api/quality/latest': typeof ApiQualityLatestRoute
  '/api/quality/projects': typeof ApiQualityProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/context': typeof ContextRoute
  '/limits': typeof LimitsRoute
  '/live': typeof LiveRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/api/agent-balances': typeof ApiAgentBalancesRoute
  '/api/analysis': typeof ApiAnalysisRouteWithChildren
  '/api/context': typeof ApiContextRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/live': typeof ApiLiveRoute
  '/api/malformed': typeof ApiMalformedRoute
  '/api/md-browser': typeof ApiMdBrowserRoute
  '/api/parallel-agents': typeof ApiParallelAgentsRouteWithChildren
  '/api/pipelines': typeof ApiPipelinesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-limits': typeof ApiProviderLimitsRouteWithChildren
  '/api/provider_limits': typeof ApiProvider_limitsRouteWithChildren
  '/api/runs': typeof ApiRunsRoute
  '/api/secondary': typeof ApiSecondaryRoute
  '/api/summary': typeof ApiSummaryRoute
  '/api/token-consumption': typeof ApiTokenConsumptionRoute
  '/api/token_consumption': typeof ApiToken_consumptionRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/dashboard/limits': typeof DashboardLimitsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/runs': typeof DashboardRunsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/analysis/document': typeof ApiAnalysisDocumentRoute
  '/api/analysis/plans': typeof ApiAnalysisPlansRoute
  '/api/charts/model-quality': typeof ApiChartsModelQualityRoute
  '/api/charts/quality': typeof ApiChartsQualityRoute
  '/api/parallel-agents/models': typeof ApiParallelAgentsModelsRoute
  '/api/provider-limits/profile': typeof ApiProviderLimitsProfileRoute
  '/api/provider_limits/profile': typeof ApiProvider_limitsProfileRoute
  '/api/quality/history': typeof ApiQualityHistoryRoute
  '/api/quality/latest': typeof ApiQualityLatestRoute
  '/api/quality/projects': typeof ApiQualityProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/context': typeof ContextRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/limits': typeof LimitsRoute
  '/live': typeof LiveRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/api/agent-balances': typeof ApiAgentBalancesRoute
  '/api/analysis': typeof ApiAnalysisRouteWithChildren
  '/api/context': typeof ApiContextRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/live': typeof ApiLiveRoute
  '/api/malformed': typeof ApiMalformedRoute
  '/api/md-browser': typeof ApiMdBrowserRoute
  '/api/parallel-agents': typeof ApiParallelAgentsRouteWithChildren
  '/api/pipelines': typeof ApiPipelinesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/provider-limits': typeof ApiProviderLimitsRouteWithChildren
  '/api/provider_limits': typeof ApiProvider_limitsRouteWithChildren
  '/api/runs': typeof ApiRunsRoute
  '/api/secondary': typeof ApiSecondaryRoute
  '/api/summary': typeof ApiSummaryRoute
  '/api/token-consumption': typeof ApiTokenConsumptionRoute
  '/api/token_consumption': typeof ApiToken_consumptionRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/dashboard/limits': typeof DashboardLimitsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/pipelines': typeof DashboardPipelinesRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/runs': typeof DashboardRunsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/analysis/document': typeof ApiAnalysisDocumentRoute
  '/api/analysis/plans': typeof ApiAnalysisPlansRoute
  '/api/charts/model-quality': typeof ApiChartsModelQualityRoute
  '/api/charts/quality': typeof ApiChartsQualityRoute
  '/api/parallel-agents/models': typeof ApiParallelAgentsModelsRoute
  '/api/provider-limits/profile': typeof ApiProviderLimitsProfileRoute
  '/api/provider_limits/profile': typeof ApiProvider_limitsProfileRoute
  '/api/quality/history': typeof ApiQualityHistoryRoute
  '/api/quality/latest': typeof ApiQualityLatestRoute
  '/api/quality/projects': typeof ApiQualityProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/context'
    | '/dashboard'
    | '/limits'
    | '/live'
    | '/overview'
    | '/pipelines'
    | '/quality'
    | '/runs'
    | '/settings'
    | '/tokens'
    | '/usage'
    | '/wiki'
    | '/api/agent-balances'
    | '/api/analysis'
    | '/api/context'
    | '/api/document'
    | '/api/live'
    | '/api/malformed'
    | '/api/md-browser'
    | '/api/parallel-agents'
    | '/api/pipelines'
    | '/api/projects'
    | '/api/provider-limits'
    | '/api/provider_limits'
    | '/api/runs'
    | '/api/secondary'
    | '/api/summary'
    | '/api/token-consumption'
    | '/api/token_consumption'
    | '/dashboard/analysis'
    | '/dashboard/limits'
    | '/dashboard/live'
    | '/dashboard/overview'
    | '/dashboard/pipelines'
    | '/dashboard/quality'
    | '/dashboard/runs'
    | '/dashboard/tokens'
    | '/dashboard/'
    | '/api/analysis/document'
    | '/api/analysis/plans'
    | '/api/charts/model-quality'
    | '/api/charts/quality'
    | '/api/parallel-agents/models'
    | '/api/provider-limits/profile'
    | '/api/provider_limits/profile'
    | '/api/quality/history'
    | '/api/quality/latest'
    | '/api/quality/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/context'
    | '/limits'
    | '/live'
    | '/overview'
    | '/pipelines'
    | '/quality'
    | '/runs'
    | '/settings'
    | '/tokens'
    | '/usage'
    | '/wiki'
    | '/api/agent-balances'
    | '/api/analysis'
    | '/api/context'
    | '/api/document'
    | '/api/live'
    | '/api/malformed'
    | '/api/md-browser'
    | '/api/parallel-agents'
    | '/api/pipelines'
    | '/api/projects'
    | '/api/provider-limits'
    | '/api/provider_limits'
    | '/api/runs'
    | '/api/secondary'
    | '/api/summary'
    | '/api/token-consumption'
    | '/api/token_consumption'
    | '/dashboard/analysis'
    | '/dashboard/limits'
    | '/dashboard/live'
    | '/dashboard/overview'
    | '/dashboard/pipelines'
    | '/dashboard/quality'
    | '/dashboard/runs'
    | '/dashboard/tokens'
    | '/dashboard'
    | '/api/analysis/document'
    | '/api/analysis/plans'
    | '/api/charts/model-quality'
    | '/api/charts/quality'
    | '/api/parallel-agents/models'
    | '/api/provider-limits/profile'
    | '/api/provider_limits/profile'
    | '/api/quality/history'
    | '/api/quality/latest'
    | '/api/quality/projects'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/context'
    | '/dashboard'
    | '/limits'
    | '/live'
    | '/overview'
    | '/pipelines'
    | '/quality'
    | '/runs'
    | '/settings'
    | '/tokens'
    | '/usage'
    | '/wiki'
    | '/api/agent-balances'
    | '/api/analysis'
    | '/api/context'
    | '/api/document'
    | '/api/live'
    | '/api/malformed'
    | '/api/md-browser'
    | '/api/parallel-agents'
    | '/api/pipelines'
    | '/api/projects'
    | '/api/provider-limits'
    | '/api/provider_limits'
    | '/api/runs'
    | '/api/secondary'
    | '/api/summary'
    | '/api/token-consumption'
    | '/api/token_consumption'
    | '/dashboard/analysis'
    | '/dashboard/limits'
    | '/dashboard/live'
    | '/dashboard/overview'
    | '/dashboard/pipelines'
    | '/dashboard/quality'
    | '/dashboard/runs'
    | '/dashboard/tokens'
    | '/dashboard/'
    | '/api/analysis/document'
    | '/api/analysis/plans'
    | '/api/charts/model-quality'
    | '/api/charts/quality'
    | '/api/parallel-agents/models'
    | '/api/provider-limits/profile'
    | '/api/provider_limits/profile'
    | '/api/quality/history'
    | '/api/quality/latest'
    | '/api/quality/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ContextRoute: typeof ContextRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LimitsRoute: typeof LimitsRoute
  LiveRoute: typeof LiveRoute
  OverviewRoute: typeof OverviewRoute
  PipelinesRoute: typeof PipelinesRoute
  QualityRoute: typeof QualityRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  TokensRoute: typeof TokensRoute
  UsageRoute: typeof UsageRoute
  WikiRoute: typeof WikiRoute
  ApiAgentBalancesRoute: typeof ApiAgentBalancesRoute
  ApiAnalysisRoute: typeof ApiAnalysisRouteWithChildren
  ApiContextRoute: typeof ApiContextRoute
  ApiDocumentRoute: typeof ApiDocumentRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiMalformedRoute: typeof ApiMalformedRoute
  ApiMdBrowserRoute: typeof ApiMdBrowserRoute
  ApiParallelAgentsRoute: typeof ApiParallelAgentsRouteWithChildren
  ApiPipelinesRoute: typeof ApiPipelinesRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiProviderLimitsRoute: typeof ApiProviderLimitsRouteWithChildren
  ApiProvider_limitsRoute: typeof ApiProvider_limitsRouteWithChildren
  ApiRunsRoute: typeof ApiRunsRoute
  ApiSecondaryRoute: typeof ApiSecondaryRoute
  ApiSummaryRoute: typeof ApiSummaryRoute
  ApiTokenConsumptionRoute: typeof ApiTokenConsumptionRoute
  ApiToken_consumptionRoute: typeof ApiToken_consumptionRoute
  ApiChartsModelQualityRoute: typeof ApiChartsModelQualityRoute
  ApiChartsQualityRoute: typeof ApiChartsQualityRoute
  ApiQualityHistoryRoute: typeof ApiQualityHistoryRoute
  ApiQualityLatestRoute: typeof ApiQualityLatestRoute
  ApiQualityProjectsRoute: typeof ApiQualityProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tokens': {
      id: '/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof DashboardTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs': {
      id: '/dashboard/runs'
      path: '/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof DashboardRunsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quality': {
      id: '/dashboard/quality'
      path: '/quality'
      fullPath: '/dashboard/quality'
      preLoaderRoute: typeof DashboardQualityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pipelines': {
      id: '/dashboard/pipelines'
      path: '/pipelines'
      fullPath: '/dashboard/pipelines'
      preLoaderRoute: typeof DashboardPipelinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/limits': {
      id: '/dashboard/limits'
      path: '/limits'
      fullPath: '/dashboard/limits'
      preLoaderRoute: typeof DashboardLimitsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analysis': {
      id: '/dashboard/analysis'
      path: '/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof DashboardAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/token_consumption': {
      id: '/api/token_consumption'
      path: '/api/token_consumption'
      fullPath: '/api/token_consumption'
      preLoaderRoute: typeof ApiToken_consumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token-consumption': {
      id: '/api/token-consumption'
      path: '/api/token-consumption'
      fullPath: '/api/token-consumption'
      preLoaderRoute: typeof ApiTokenConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary': {
      id: '/api/summary'
      path: '/api/summary'
      fullPath: '/api/summary'
      preLoaderRoute: typeof ApiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/secondary': {
      id: '/api/secondary'
      path: '/api/secondary'
      fullPath: '/api/secondary'
      preLoaderRoute: typeof ApiSecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider_limits': {
      id: '/api/provider_limits'
      path: '/api/provider_limits'
      fullPath: '/api/provider_limits'
      preLoaderRoute: typeof ApiProvider_limitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-limits': {
      id: '/api/provider-limits'
      path: '/api/provider-limits'
      fullPath: '/api/provider-limits'
      preLoaderRoute: typeof ApiProviderLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipelines': {
      id: '/api/pipelines'
      path: '/api/pipelines'
      fullPath: '/api/pipelines'
      preLoaderRoute: typeof ApiPipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parallel-agents': {
      id: '/api/parallel-agents'
      path: '/api/parallel-agents'
      fullPath: '/api/parallel-agents'
      preLoaderRoute: typeof ApiParallelAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/md-browser': {
      id: '/api/md-browser'
      path: '/api/md-browser'
      fullPath: '/api/md-browser'
      preLoaderRoute: typeof ApiMdBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/malformed': {
      id: '/api/malformed'
      path: '/api/malformed'
      fullPath: '/api/malformed'
      preLoaderRoute: typeof ApiMalformedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document': {
      id: '/api/document'
      path: '/api/document'
      fullPath: '/api/document'
      preLoaderRoute: typeof ApiDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context': {
      id: '/api/context'
      path: '/api/context'
      fullPath: '/api/context'
      preLoaderRoute: typeof ApiContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis': {
      id: '/api/analysis'
      path: '/api/analysis'
      fullPath: '/api/analysis'
      preLoaderRoute: typeof ApiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-balances': {
      id: '/api/agent-balances'
      path: '/api/agent-balances'
      fullPath: '/api/agent-balances'
      preLoaderRoute: typeof ApiAgentBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quality/projects': {
      id: '/api/quality/projects'
      path: '/api/quality/projects'
      fullPath: '/api/quality/projects'
      preLoaderRoute: typeof ApiQualityProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quality/latest': {
      id: '/api/quality/latest'
      path: '/api/quality/latest'
      fullPath: '/api/quality/latest'
      preLoaderRoute: typeof ApiQualityLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quality/history': {
      id: '/api/quality/history'
      path: '/api/quality/history'
      fullPath: '/api/quality/history'
      preLoaderRoute: typeof ApiQualityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider_limits/profile': {
      id: '/api/provider_limits/profile'
      path: '/profile'
      fullPath: '/api/provider_limits/profile'
      preLoaderRoute: typeof ApiProvider_limitsProfileRouteImport
      parentRoute: typeof ApiProvider_limitsRoute
    }
    '/api/provider-limits/profile': {
      id: '/api/provider-limits/profile'
      path: '/profile'
      fullPath: '/api/provider-limits/profile'
      preLoaderRoute: typeof ApiProviderLimitsProfileRouteImport
      parentRoute: typeof ApiProviderLimitsRoute
    }
    '/api/parallel-agents/models': {
      id: '/api/parallel-agents/models'
      path: '/models'
      fullPath: '/api/parallel-agents/models'
      preLoaderRoute: typeof ApiParallelAgentsModelsRouteImport
      parentRoute: typeof ApiParallelAgentsRoute
    }
    '/api/charts/quality': {
      id: '/api/charts/quality'
      path: '/api/charts/quality'
      fullPath: '/api/charts/quality'
      preLoaderRoute: typeof ApiChartsQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/model-quality': {
      id: '/api/charts/model-quality'
      path: '/api/charts/model-quality'
      fullPath: '/api/charts/model-quality'
      preLoaderRoute: typeof ApiChartsModelQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/plans': {
      id: '/api/analysis/plans'
      path: '/plans'
      fullPath: '/api/analysis/plans'
      preLoaderRoute: typeof ApiAnalysisPlansRouteImport
      parentRoute: typeof ApiAnalysisRoute
    }
    '/api/analysis/document': {
      id: '/api/analysis/document'
      path: '/document'
      fullPath: '/api/analysis/document'
      preLoaderRoute: typeof ApiAnalysisDocumentRouteImport
      parentRoute: typeof ApiAnalysisRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalysisRoute: typeof DashboardAnalysisRoute
  DashboardLimitsRoute: typeof DashboardLimitsRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardPipelinesRoute: typeof DashboardPipelinesRoute
  DashboardQualityRoute: typeof DashboardQualityRoute
  DashboardRunsRoute: typeof DashboardRunsRoute
  DashboardTokensRoute: typeof DashboardTokensRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalysisRoute: DashboardAnalysisRoute,
  DashboardLimitsRoute: DashboardLimitsRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardPipelinesRoute: DashboardPipelinesRoute,
  DashboardQualityRoute: DashboardQualityRoute,
  DashboardRunsRoute: DashboardRunsRoute,
  DashboardTokensRoute: DashboardTokensRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAnalysisRouteChildren {
  ApiAnalysisDocumentRoute: typeof ApiAnalysisDocumentRoute
  ApiAnalysisPlansRoute: typeof ApiAnalysisPlansRoute
}

const ApiAnalysisRouteChildren: ApiAnalysisRouteChildren = {
  ApiAnalysisDocumentRoute: ApiAnalysisDocumentRoute,
  ApiAnalysisPlansRoute: ApiAnalysisPlansRoute,
}

const ApiAnalysisRouteWithChildren = ApiAnalysisRoute._addFileChildren(
  ApiAnalysisRouteChildren,
)

interface ApiParallelAgentsRouteChildren {
  ApiParallelAgentsModelsRoute: typeof ApiParallelAgentsModelsRoute
}

const ApiParallelAgentsRouteChildren: ApiParallelAgentsRouteChildren = {
  ApiParallelAgentsModelsRoute: ApiParallelAgentsModelsRoute,
}

const ApiParallelAgentsRouteWithChildren =
  ApiParallelAgentsRoute._addFileChildren(ApiParallelAgentsRouteChildren)

interface ApiProviderLimitsRouteChildren {
  ApiProviderLimitsProfileRoute: typeof ApiProviderLimitsProfileRoute
}

const ApiProviderLimitsRouteChildren: ApiProviderLimitsRouteChildren = {
  ApiProviderLimitsProfileRoute: ApiProviderLimitsProfileRoute,
}

const ApiProviderLimitsRouteWithChildren =
  ApiProviderLimitsRoute._addFileChildren(ApiProviderLimitsRouteChildren)

interface ApiProvider_limitsRouteChildren {
  ApiProvider_limitsProfileRoute: typeof ApiProvider_limitsProfileRoute
}

const ApiProvider_limitsRouteChildren: ApiProvider_limitsRouteChildren = {
  ApiProvider_limitsProfileRoute: ApiProvider_limitsProfileRoute,
}

const ApiProvider_limitsRouteWithChildren =
  ApiProvider_limitsRoute._addFileChildren(ApiProvider_limitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ContextRoute: ContextRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LimitsRoute: LimitsRoute,
  LiveRoute: LiveRoute,
  OverviewRoute: OverviewRoute,
  PipelinesRoute: PipelinesRoute,
  QualityRoute: QualityRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  TokensRoute: TokensRoute,
  UsageRoute: UsageRoute,
  WikiRoute: WikiRoute,
  ApiAgentBalancesRoute: ApiAgentBalancesRoute,
  ApiAnalysisRoute: ApiAnalysisRouteWithChildren,
  ApiContextRoute: ApiContextRoute,
  ApiDocumentRoute: ApiDocumentRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiMalformedRoute: ApiMalformedRoute,
  ApiMdBrowserRoute: ApiMdBrowserRoute,
  ApiParallelAgentsRoute: ApiParallelAgentsRouteWithChildren,
  ApiPipelinesRoute: ApiPipelinesRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiProviderLimitsRoute: ApiProviderLimitsRouteWithChildren,
  ApiProvider_limitsRoute: ApiProvider_limitsRouteWithChildren,
  ApiRunsRoute: ApiRunsRoute,
  ApiSecondaryRoute: ApiSecondaryRoute,
  ApiSummaryRoute: ApiSummaryRoute,
  ApiTokenConsumptionRoute: ApiTokenConsumptionRoute,
  ApiToken_consumptionRoute: ApiToken_consumptionRoute,
  ApiChartsModelQualityRoute: ApiChartsModelQualityRoute,
  ApiChartsQualityRoute: ApiChartsQualityRoute,
  ApiQualityHistoryRoute: ApiQualityHistoryRoute,
  ApiQualityLatestRoute: ApiQualityLatestRoute,
  ApiQualityProjectsRoute: ApiQualityProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
