#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { validateReviewOutcome } from './tbr.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const STATE = path.join(ROOT, 'state');
const OPERATOR_TYPES = new Set(['OpPreflight','OpContextPack','OpSpawn','OpRoute','OpGate','OpReview','OpUserCorrection','OpRuleAction','OpQualityReview','OpReleaseDecision','OpDecision']);
function slug(v){return String(v||'unknown').replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||'unknown'}
function normalizePlan(v){const raw=String(v||'unknown-plan').trim()||'unknown-plan';const m=raw.match(/^(?:plan-)?(\d{1,3})$/i);return m?`plan-${m[1].padStart(3,'0')}`:raw}
function parse(argv){const a={project:ROOT,plan:'unknown-plan',actor:'orchestrator',dryRun:false};for(let i=0;i<argv.length;i++){const x=argv[i];if(x==='--dry-run')a.dryRun=true;else if(x.startsWith('--'))a[x.slice(2).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=argv[++i];}return a}
function obj(raw,name){if(!raw)return undefined;const o=JSON.parse(raw);if(!o||typeof o!=='object'||Array.isArray(o))throw new Error(`${name} must be JSON object`);return o}
function validate(r){const e=[];if(!OPERATOR_TYPES.has(r.operator_type))e.push(`operator_type must be one of ${[...OPERATOR_TYPES].sort()}`);for(const k of ['timestamp','project_path','pipeline_id','plan_key','operator_type'])if(!r[k])e.push(`missing required field: ${k}`);if(r.operator_type==='OpRoute'){if(!r.logical_decision)e.push('OpRoute requires logical_decision');if(!r.physical_action)e.push('OpRoute requires physical_action')}if(r.operator_type==='OpRuleAction')for(const k of ['rule_path','action','approval_source','expected_impact_dimension'])if(!r[k])e.push(`OpRuleAction missing ${k}`);if(r.operator_type==='OpUserCorrection'&&!(r.reason||r.logical_decision?.summary))e.push('OpUserCorrection requires --reason or logical_json.summary');if(r.operator_type==='OpReleaseDecision'&&!(r.reason||r.source_artifact||r.physical_action))e.push('OpReleaseDecision requires --reason, --source-artifact, or --physical-json');if(r.operator_type==='OpDecision')for(const k of ['decision_type','target_operator','reason','approved_by'])if(!r[k])e.push(`OpDecision missing ${k}`);return e}
try{const a=parse(process.argv.slice(2));if(!a.pipelineId||!a.operatorType){console.error('missing --pipeline-id or --operator-type');process.exit(2)}const review=a.reviewOutcomeJson?validateReviewOutcome(obj(a.reviewOutcomeJson,'review-outcome-json')):undefined;if(review&&!review.ok)throw new Error(`Invalid review outcome: ${review.code}`);const project=path.resolve(a.project);const rec={timestamp:new Date().toISOString(),project_path:project,project_slug:path.basename(project),pipeline_id:slug(a.pipelineId),plan_key:normalizePlan(a.plan),operator_type:a.operatorType,actor:a.actor};for(const [k,v] of Object.entries({agent:a.agent,source_artifact:a.sourceArtifact,gate:a.gate,severity:a.severity,confidence:a.confidence,reason:a.reason}))if(v)rec[k]=v;if(a.logicalJson)rec.logical_decision=obj(a.logicalJson,'logical_decision');if(a.physicalJson)rec.physical_action=obj(a.physicalJson,'physical_action');if(review)rec.review_outcome=review.value;if(a.extraJson)Object.assign(rec,obj(a.extraJson,'extra-json'));const errs=validate(rec);if(errs.length){console.error('Invalid operator event:');errs.forEach(x=>console.error(`- ${x}`));process.exit(2)}if(a.dryRun){console.log(JSON.stringify(rec,null,2));process.exit(0)}const dir=path.join(STATE,'orchestrator-events',slug(path.basename(project)));mkdirSync(dir,{recursive:true});const out=path.join(dir,`${rec.pipeline_id}.jsonl`);writeFileSync(out,JSON.stringify(rec)+'\n',{flag:'a'});console.log(out)}catch(e){console.error(e.message);process.exit(1)}
