import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import * as admissionApi from './rule-learning-admission.mjs';
import { admitRuleLearningCandidate, prepareSemanticReviewContext, semanticVoteDigest } from './rule-learning-admission.mjs';
import { buildRuleLearningCandidate } from './rule-learning-candidate.mjs';
import { createRuleLearningFinding, createRuleLearningSupport, findingDigest, lessonCode } from './rule-learning-contracts.mjs';
import { openRuleLifecycleStore } from './rule-lifecycle-store.mjs';

const hex = (char, length = 64) => char.repeat(length);
const scopeA = 'a'.repeat(24);
const scopeB = 'b'.repeat(24);
const reviewers = ['one', 'two', 'three'].map((name) => ({ principal: `reviewer:${name}`, backend: `backend:${name}`, provider: 'provider', model: 'model' }));
const finding = ({ scope = scopeA, id = 'a', repo = 'b' } = {}) => createRuleLearningFinding({ schema_version: 'pidex-rule-learning-finding-v1', finding_id: `finding:${id.repeat(32)}`, producer: 'pidex-retrospective', completed_run_id: `run:completed-${id}`, plan_id: 'plan:047', project_scope_id: scope, repository_identity: `repo:${hex(repo)}`, taxonomy: 'delivery_failure', affected_agent: 'pidex-implementer', affected_phase: 'implementation', recurrence_key: 'quality:validation-missing', lesson_summary: 'Safe recurrence.', evidence_digests: [hex(id)], occurred_at: '2026-08-13T00:00:00.000Z', redaction_classes: ['none'] });
const support = (tier, findings) => createRuleLearningSupport({ schema_version: 'pidex-rule-learning-support-v1', tier, taxonomy: 'delivery_failure', affected_agent: 'pidex-implementer', affected_phase: 'implementation', recurrence_key: 'quality:validation-missing', lesson_code: lessonCode({ taxonomy: 'delivery_failure', affected_agent: 'pidex-implementer', affected_phase: 'implementation', recurrence_key: 'quality:validation-missing' }), occurrence_count: findings.length, scope_count: tier === 'global' ? findings.length : 1, finding_digests: findings.map(findingDigest).sort() });
const generator = () => ({ slug: 'validate-contract', applicability: ['implementation'], instruction: 'Validate contract.', trigger: 'Before handoff.', expected_evidence: 'Focused checks pass.', failure_behavior: 'Defer publication.', rationale: 'Repeated safe support.' });
function authorityConfig(findings) { const authority_digest = hex('9'); const source = (item) => ({ finding_id: item.finding_id, snapshot: { repository: item.repository_identity, scope_id: item.project_scope_id, tier: 'project', enabled: true, protected: false, repository_identity: item.repository_identity } }); const target = (tier, scope_id, repository, scope_digest) => ({ repository, scope_id, tier, enabled: true, protected: false, scope_digest, predecessor: `commit:${hex(tier === 'global' ? '7' : '6', 40)}`, authority_digest, applicable_descriptors: [{ descriptor_digest: hex('5') }], existing: [{ rule_id: 'project:other', content_hash: hex('0'), candidate_digest: hex('1'), predecessor_commit: `commit:${hex('6', 40)}` }] }); return { enrollment: { authority_digest, sources: findings.map(source), targets: { project: target('project', scopeA, 'repo:target', `${scopeA}${'d'.repeat(40)}`), global: target('global', null, 'repo:global', hex('d')) }, policy: { id: 'pidex-living-rule-admission-v1', version: '1', digest: hex('3') }, generator_identity: { principal: 'generator:configured', attempt_id: 'attempt:generator-001' } }, reviewers: { configuration_generation: 'config:1', generator_principal: 'generator:configured', now: '2026-08-13T01:00:00.000Z', principals: reviewers.map((reviewer) => ({ ...reviewer })) } }; }
function setup({ tier = 'project', mutate = (value) => value } = {}) { const findings = tier === 'global' ? [finding(), finding({ scope: scopeB, id: 'b', repo: 'c' })] : [finding()]; const authority = mutate(authorityConfig(findings)); const stateRoot = mkdtempSync(path.join(os.tmpdir(), 'pidex-learning-admission-')); const store = openRuleLifecycleStore({ stateRoot, learningAuthority: authority }); for (const item of findings) store.enroll({ repository: item.repository_identity, scope_id: item.project_scope_id, remote: `https://example.invalid/${item.repository_identity}`, branch: 'main' }); for (const target of Object.values(authority.enrollment.targets)) store.enroll({ repository: target.repository, scope_id: target.scope_id, remote: `https://example.invalid/${target.repository}`, branch: 'main' }); const candidate = buildRuleLearningCandidate({ support: support(tier, findings), findings, authority: store.mintRuleLearningEnrollmentAuthority(), generator }).candidate; return { stateRoot, store, candidate }; }
function close({ stateRoot, store }) { store.close(); rmSync(stateRoot, { recursive: true, force: true }); }
function votes(context, count = 2, mutate = (vote) => vote) { return reviewers.slice(0, count).map((reviewer) => mutate({ schema_version: 'pidex-living-rule-semantic-vote-v1', candidate_digest: context.candidate_digest, candidate_content_hash: context.candidate_content_hash, admission_policy_digest: context.admission_policy_digest, admission_policy_version: context.admission_policy_version, tier: context.tier, repository_scope_digest: context.repository_scope_digest, reviewer_principal: reviewer.principal, backend_identity: reviewer.backend, provider: reviewer.provider, model: reviewer.model, configuration_generation: 'config:1', attempt_id: `attempt:${reviewer.principal.slice(9)}`, nonce: `nonce:${reviewer.principal.slice(9)}`, issued_at: '2026-08-13T01:00:00.000Z', expires_at: '2026-08-13T01:05:00.000Z', decision: 'accept' }, reviewer)); }
function admit(fixture, envelopes, context = prepareSemanticReviewContext({ candidate: fixture.candidate }), authority = fixture.store.mintRuleLearningReviewerAuthority()) { return admitRuleLearningCandidate({ candidate: fixture.candidate, context, votes: envelopes, reviewer_authority: authority }); }
function assertVoteDefers(change) { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context, 2, change)).status, 'deferred'); } finally { close(fixture); } }
function claimCount(stateRoot) { const db = new DatabaseSync(path.join(stateRoot, 'quality', 'rule-lifecycle', 'lifecycle.sqlite'), { readOnly: true }); try { return db.prepare('SELECT COUNT(*) AS count FROM rule_learning_vote_claim').get().count; } finally { db.close(); } }
function reopen(fixture) { fixture.store.close(); const store = openRuleLifecycleStore({ stateRoot: fixture.stateRoot, learningAuthority: authorityConfig([finding()]) }); for (const item of [finding()]) store.enroll({ repository: item.repository_identity, scope_id: item.project_scope_id, remote: `https://example.invalid/${item.repository_identity}`, branch: 'main' }); for (const target of Object.values(authorityConfig([finding()]).enrollment.targets)) store.enroll({ repository: target.repository, scope_id: target.scope_id, remote: `https://example.invalid/${target.repository}`, branch: 'main' }); return store; }

test('admission has no caller-owned reviewer factory or TX/Git import', async () => { assert.equal(admissionApi.createReviewerAuthorityAdapter, undefined); const source = await import('node:fs/promises').then(({ readFile }) => readFile(new URL('./rule-learning-admission.mjs', import.meta.url), 'utf8')); assert.doesNotMatch(source, /rule-publication|rule-git/); });
test('admission requires exact full-digest semantic context', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(context.candidate_digest, fixture.candidate.candidate_digest); assert.equal(admit(fixture, votes(context), { ...context, candidate_digest: hex('0') }).status, 'deferred'); assert.equal(admitRuleLearningCandidate({ candidate: { ...fixture.candidate, rule_id: `${fixture.candidate.rule_id}x` }, context, votes: votes(context), reviewer_authority: fixture.store.mintRuleLearningReviewerAuthority() }).status, 'deferred'); } finally { close(fixture); } });
test('admission uses deterministic project-two and global-three reviewer quorums', () => { const project = setup(); const global = setup({ tier: 'global' }); try { assert.equal(admit(project, votes(prepareSemanticReviewContext({ candidate: project.candidate }), 2)).status, 'admitted'); assert.equal(admit(global, votes(prepareSemanticReviewContext({ candidate: global.candidate }), 2)).status, 'deferred'); assert.equal(admit(global, votes(prepareSemanticReviewContext({ candidate: global.candidate }), 3)).status, 'admitted'); } finally { close(project); close(global); } });
test('admission defers malformed vote', () => { assertVoteDefers((vote) => ({ ...vote, schema_version: 'bad' })); });
test('admission defers abstaining vote', () => { assertVoteDefers((vote) => ({ ...vote, decision: 'abstain' })); });
test('admission defers disagreeing vote', () => { assertVoteDefers((vote) => ({ ...vote, decision: 'reject' })); });
test('admission defers missing reviewer', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context, 1)).status, 'deferred'); } finally { close(fixture); } });
test('admission defers generator voter', () => { const fixture = setup({ mutate: (value) => { value.reviewers.principals[0].principal = 'generator:configured'; return value; } }); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context)).status, 'deferred'); } finally { close(fixture); } });
test('admission defers backend alias', () => { const fixture = setup({ mutate: (value) => { value.reviewers.principals[1].backend = value.reviewers.principals[0].backend; return value; } }); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context)).status, 'deferred'); } finally { close(fixture); } });
test('admission defers copied attempt', () => { assertVoteDefers((vote) => ({ ...vote, attempt_id: 'attempt:copied' })); });
test('admission defers stale configuration generation', () => { assertVoteDefers((vote) => ({ ...vote, configuration_generation: 'config:old' })); });
test('admission defers expired vote', () => { assertVoteDefers((vote) => ({ ...vote, expires_at: '2026-08-13T01:00:00.000Z' })); });
test('admission defers context drift', () => { assertVoteDefers((vote) => ({ ...vote, repository_scope_digest: hex('0') })); });
test('admission defers durable replay across remint and restart', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); const envelopes = votes(context); assert.equal(admit(fixture, envelopes, context, fixture.store.mintRuleLearningReviewerAuthority()).status, 'admitted'); assert.equal(claimCount(fixture.stateRoot), 2); assert.equal(admit(fixture, envelopes, context, fixture.store.mintRuleLearningReviewerAuthority()).status, 'deferred'); const reopened = reopen(fixture); assert.equal(admitRuleLearningCandidate({ candidate: fixture.candidate, context, votes: envelopes, reviewer_authority: reopened.mintRuleLearningReviewerAuthority() }).status, 'deferred'); reopened.close(); } finally { rmSync(fixture.stateRoot, { recursive: true, force: true }); } });
test('admission rejects provider, model, or generation mismatch before durable claim', () => { for (const change of [(vote) => ({ ...vote, provider: 'wrong-provider' }), (vote) => ({ ...vote, model: 'wrong-model' }), (vote) => ({ ...vote, configuration_generation: 'config:old' })]) { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context, 2, change)).status, 'deferred'); assert.equal(claimCount(fixture.stateRoot), 0); } finally { close(fixture); } } });
test('two same-root handles atomically consume one quorum with no partial claim', () => { const fixture = setup(); let second; try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); const envelopes = votes(context); second = openRuleLifecycleStore({ stateRoot: fixture.stateRoot, learningAuthority: authorityConfig([finding()]) }); const results = [admit(fixture, envelopes, context, fixture.store.mintRuleLearningReviewerAuthority()), admitRuleLearningCandidate({ candidate: fixture.candidate, context, votes: envelopes, reviewer_authority: second.mintRuleLearningReviewerAuthority() })].map((result) => result.status).sort(); assert.deepEqual(results, ['admitted', 'deferred']); assert.equal(claimCount(fixture.stateRoot), 2); } finally { second?.close(); close(fixture); } });
test('claim transaction rolls back every quorum vote when SQLite insert fails', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); const db = new DatabaseSync(path.join(fixture.stateRoot, 'quality', 'rule-lifecycle', 'lifecycle.sqlite')); db.exec("CREATE TRIGGER rule_learning_vote_claim_abort BEFORE INSERT ON rule_learning_vote_claim WHEN NEW.reviewer_principal = 'reviewer:two' BEGIN SELECT RAISE(ABORT, 'claim abort'); END"); db.close(); assert.equal(admit(fixture, votes(context)).status, 'deferred'); assert.equal(claimCount(fixture.stateRoot), 0); } finally { close(fixture); } });
test('admission defers cross-store reviewer authority', () => { const fixture = setup(); const other = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context), context, other.store.mintRuleLearningReviewerAuthority()).status, 'deferred'); } finally { close(fixture); close(other); } });
test('admission defers closed-store reviewer authority', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); const stale = fixture.store.mintRuleLearningReviewerAuthority(); fixture.store.close(); assert.equal(admitRuleLearningCandidate({ candidate: fixture.candidate, context, votes: votes(context), reviewer_authority: stale }).status, 'deferred'); } finally { rmSync(fixture.stateRoot, { recursive: true, force: true }); } });
test('admission allows sibling with same predecessor', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context)).status, 'admitted'); } finally { close(fixture); } });
test('admission defers deterministic same-identity conflict', () => { const fixture = setup({ mutate: (value) => { value.enrollment.targets.project.existing = [{ rule_id: `project:${scopeA}:pidex-implementer:validate-contract`, candidate_digest: hex('0'), content_hash: hex('0') }]; return value; } }); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context)).status, 'deferred'); } finally { close(fixture); } });
test('admission defers deterministic duplicate-content conflict', () => { const body = '# validate-contract\n\n## Instruction\nValidate contract.\n\n## Trigger\nBefore handoff.\n\n## Expected evidence\nFocused checks pass.\n\n## Failure behavior\nDefer publication.\n\n## Rationale\nRepeated safe support.\n'; const fixture = setup({ mutate: (value) => { value.enrollment.targets.project.existing = [{ rule_id: 'project:other', candidate_digest: hex('0'), content_hash: createHash('sha256').update(body, 'utf8').digest('hex') }]; return value; } }); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); assert.equal(admit(fixture, votes(context)).status, 'deferred'); } finally { close(fixture); } });
test('semantic vote digest is deterministic and binds every supplied vote field', () => { const fixture = setup(); try { const context = prepareSemanticReviewContext({ candidate: fixture.candidate }); const [vote] = votes(context); assert.equal(semanticVoteDigest(vote), semanticVoteDigest({ ...vote })); for (const field of ['candidate_digest', 'candidate_content_hash', 'admission_policy_digest', 'admission_policy_version', 'tier', 'repository_scope_digest', 'reviewer_principal', 'backend_identity', 'provider', 'model', 'configuration_generation', 'attempt_id', 'nonce', 'issued_at', 'expires_at']) assert.notEqual(semanticVoteDigest({ ...vote, [field]: `${vote[field]}x` }), semanticVoteDigest(vote), field); } finally { close(fixture); } });
