import { promises as fs } from 'node:fs';
import path from 'node:path';

const PIDEX_ROOT = path.resolve(process.cwd(), '..');
const DEFAULT_CONFIG = path.join(PIDEX_ROOT, 'config', 'contract-governor.json');
const LOCAL_CONFIG = path.join(PIDEX_ROOT, 'config', 'contract-governor.local.json');
const STATE_DIR = path.join(PIDEX_ROOT, 'state', 'quality', 'contract-governor');
const CORRECTIONS = path.join(PIDEX_ROOT, 'state', 'quality', 'contract-corrections.jsonl');

type AnyRecord = Record<string, any>;
async function readJson(file: string, fallback: AnyRecord = {}) { try { return JSON.parse(await fs.readFile(file, 'utf8')); } catch { return fallback; } }
async function exists(file: string) { try { await fs.stat(file); return true; } catch { return false; } }
async function walk(dir: string): Promise<string[]> { const out: string[] = []; async function rec(d: string) { const es = await fs.readdir(d, { withFileTypes: true }).catch(() => []); for (const e of es) { const p = path.join(d, e.name); if (e.isDirectory()) await rec(p); else out.push(p); } } await rec(dir); return out.sort(); }
async function readJsonl(file: string): Promise<AnyRecord[]> { try { return (await fs.readFile(file, 'utf8')).split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line)); } catch { return []; } }
function safeConfig(input: AnyRecord) { return { version: 1, enabled: Boolean(input.enabled), background: input.background !== false, mode: ['deterministic-only', 'agent-review', 'agent-review-auto-apply'].includes(input.mode) ? input.mode : 'deterministic-only', hot_mode: Boolean(input.hot_mode), auto_apply: input.hot_mode && input.auto_apply === 'low-risk' ? 'low-risk' : 'off', agent_enabled: Boolean(input.agent_enabled), model: input.model || null, escalation_model: input.escalation_model || null, effort: input.effort || 'medium', timeout_seconds: Math.max(10, Math.min(600, Number(input.timeout_seconds || 60))), max_cost_usd_per_run: Math.max(0, Number(input.max_cost_usd_per_run || 0)), max_proposals_per_run: Math.max(1, Math.min(20, Number(input.max_proposals_per_run || 5))), monitoring_window_reports: Math.max(1, Math.min(20, Number(input.monitoring_window_reports || 5))) }; }
export async function getContractGovernorStatus(root = PIDEX_ROOT) { const defaults = await readJson(path.join(root, 'config', 'contract-governor.json')); const localPath = path.join(root, 'config', 'contract-governor.local.json'); const local = await readJson(localPath, {}); const effective = safeConfig({ ...defaults, ...local }); const runFiles = (await walk(path.join(root, 'state', 'quality', 'contract-governor'))).filter((p) => p.endsWith('run.json')); const runs = (await Promise.all(runFiles.map((f) => readJson(f).then((r) => ({ ...r, path: f }))))).filter((r) => r.run_id || r.status).sort((a, b) => (Date.parse(b.timestamp || '') || 0) - (Date.parse(a.timestamp || '') || 0)).slice(0, 20); const corrections = await readJsonl(path.join(root, 'state', 'quality', 'contract-corrections.jsonl')); return { ok: true, default_config: defaults, local_config: local, effective_config: effective, local_config_exists: await exists(localPath), runs, corrections: corrections.slice(-100).reverse(), pending: corrections.filter((r) => r.status === 'pending').slice(-50).reverse(), approved: corrections.filter((r) => ['approved', 'applied'].includes(r.status)).slice(-50).reverse() }; }
export async function saveContractGovernorLocalConfig(config: AnyRecord, root = PIDEX_ROOT) { const next = safeConfig(config); await fs.mkdir(path.join(root, 'config'), { recursive: true }); await fs.writeFile(path.join(root, 'config', 'contract-governor.local.json'), `${JSON.stringify(next, null, 2)}\n`, 'utf8'); return getContractGovernorStatus(root); }
